[package]
name = "fdk-mqa-scoring-bff"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1.0"
diesel = { version = "1.4.8", features = ["postgres", "r2d2"] }
diesel_migrations = { version = "1.4.0", features = ["postgres"] }
lazy_static = "1.4.0"
mime = "0.3.16"
r2d2 = "0.8.9"
serde = { version ="1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_yaml = "0.8.24"
thiserror = "1.0.31"
tracing = "0.1.35"
tracing-subscriber =  { version = "0.3.11", features = ["json"] }
utoipa = { version = "1.1.0", features = ["actix_extras"] }
utoipa-swagger-ui = { version="1.1.0", features = ["actix-web"] }
uuid = "1.1.2"
