---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-fdk-mqa-scoring-api.yaml
  - deployment-fdk-mqa-scoring-api.yaml

images:
  - name: fdk-mqa-scoring-api
    newName: ghcr.io/informasjonsforvaltning/fdk-mqa-scoring-api
    newTag: $(GIT_COMMIT_SHA)
